on:
  # pull_request:
  #   types:
  #     - synchronize
  push:
    branches:
      - master
      - stg

name: Run tests for API

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "hello keisuke wow!"